### ISSUE TITLE
No file train_list.txt

### ISSUE THREAD

**Issue by DzigaVertoff** [human-3d/Human3D#12]
I'm trying to execute humanseg_preprocessing.py and I get this error:
FileNotFoundError: [Errno 2] No such file or directory: './data/raw/train_list.txt'

**Comment by aycatakmaz** [comment]
Hi,

Thank you very much for your interest in our work!

The file names `train_list.txt` and `validation_list.txt` are from a previous iteration of the dataset, you can simply rename the `split_train.txt` and `split_val.txt` files to `train_list.txt` and `validation_list.txt`. The files you already downloaded should be essentially the same, I think we simply renamed them at some point.

More details could be found in [this](https://github.com/human-3d/Human3D/issues/9#issuecomment-1870182864) issue.

Hope this helps!

**Comment by DzigaVertoff** [comment]
Thank you, so I suppose I should download the full 60GB dataset in order to find these files, right?

**Comment by aycatakmaz** [comment]
If you would like to train on full dataset, then yes. Otherwise, you should preprocess your own data similar to what our [preprocessing script](https://github.com/human-3d/Human3D/blob/main/datasets/preprocessing/humanseg_preprocessing.py) does. We plan to release an example script sometime soon for preprocessing users' own data, but it will be essentially an adaptation of the preprocessing script I linked.

**Comment by DzigaVertoff** [comment]
> If you would like to train on full dataset, then yes. Otherwise, you should preprocess your own data similar to what our [preprocessing script](https://github.com/human-3d/Human3D/blob/main/datasets/preprocessing/humanseg_preprocessing.py) does. We plan to release an example script sometime soon for preprocessing users' own data, but it will be essentially an adaptation of the preprocessing script I linked.

Yes, but I don't have neither split_train.txt (train_list.txt) or split_val.txt (validation_list.txt). I don't know where to find them. Do you have an example of them?

EDIT:
Found them in 60GB dataset, they are just a list of PLY files like this:
```
recording_20211004_S12_S20_01/main/frame_01141.ply
recording_20211004_S12_S20_01/main/frame_01171.ply
recording_20211004_S12_S20_01/main/frame_01201.ply
recording_20211004_S12_S20_01/main/frame_01231.ply
```
