### ISSUE TITLE
PLY file header

### ISSUE THREAD

**Issue by DzigaVertoff** [human-3d/Human3D#13]
I noticed that your PLY files have two more property than mine:
```
property uchar inst_label
property uchar label
```
What are they?

**Comment by aycatakmaz** [comment]
In our data, we added additional channels for instance labels and body_part labels in the ply files, to represent per-point labels.

Please see [this function](https://github.com/human-3d/SyntheticHumanDataset/blob/44357a05932e72f698f6dcf442cd4b20c4f0245d/utils/pc_utils.py#L114) in our data generation repository for Human3D, we have this `save_point_cloud_w_inst_label` function that saves instances and labels as additional channels in the ply file.

Instance ID values: 0 means background - 1,2,3,... mean separate human instance IDs.
Label values: 0 means background, the remaining values mean original semantic label IDs. These values are mapped to body parts using the dictionary [here](https://github.com/human-3d/Human3D/blob/7aebbb80d1481cc38867cfbe8a7493845a1f0ab2/datasets/preprocessing/humanseg_preprocessing.py#L149).

These channels are used/needed only during training, or while evaluating the metrics - so they are not relevant for the inference on an arbitrary point cloud.

Hope this helps!

**Comment by DzigaVertoff** [comment]
Thank you for explanation
