### ISSUE TITLE
Where is pointnet2 file?

### ISSUE THREAD

**Issue by jk456445** [human-3d/Human3D#4]
In the installation process, there is a part with cd . . /. . /pointnet2, but I don't have this folder. 
How can I obtain this folder and its contents?

**Comment by aycatakmaz** [comment]
We have pushed a commit that adds the pointnet2 files to the repo and updated the readme. You can find the pointnet2 folder [here](https://github.com/human-3d/Human3D/tree/main/third_party/pointnet2). Hope this helps! I am closing the issue, feel free to re-open it if you encounter any other issues regarding pointnet2 installation.
