### ISSUE TITLE
Where to get data correctly

### ISSUE THREAD

**Issue by jk456445** [human-3d/Human3D#5]
I encounter difficulty in locating the data for the following folders when retrieving information. 
I would like to inquire about the correct method for obtaining them.
![pic](https://github.com/human-3d/Human3D/assets/81965933/4b04a708-6a5a-417e-9120-02516b1ad219)

**Comment by aycatakmaz** [comment]
As mentioned in https://github.com/human-3d/SyntheticHumanDataset/blob/main/README.md, _synthetic humans_ that were placed for the Human3D project can be downloaded from [here](https://drive.google.com/file/d/1YP7SJtaAT9lIC85q3wf0X6Iaxkw_fncc/view?usp=sharing).

Scenes meshes from the ScanNet dataset, e.g. `sceneXXXX_XX_vh_clean_2.ply` and `sceneXXXX_XX_vh_clean_2.labels.ply` can be downloaded by downloading the ScanNet dataset. To read about how to download the data, please refer to https://github.com/ScanNet/ScanNet and https://www.scan-net.org/changelog#scannet-v2-2018-06-11.
