### ISSUE TITLE
running eval_human3d.sh error

### ISSUE THREAD

**Issue by ZhYuLn** [human-3d/Human3D#6]
os: ubuntu20.04
python: 3.10
cuda: 11.3
when I running `sh scripts/eval/eval_human3d.sh`, it show me the error:
```
  File "/opt/conda/envs/human3d_cuda113/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 400, in _load_single_config
    raise ValueError(
ValueError: Config logging/full must be a Dictionary, got ConfigResult
```
what can I do to resolve it?

**Comment by aycatakmaz** [comment]
Hi,

This could be an issue due to the version of the hydra package, we used hydra-core==1.0.5 in our experiments. Could you verify that you have the same version installed in your conda environment?

Best,
Ayca

**Comment by ZhYuLn** [comment]
Thank you, I replace 1.1.0 with 1.0.5 and it working fun.
