### ISSUE TITLE
How to use the pre-trained checkpoint to predict my own pointcloud?

### ISSUE THREAD

**Issue by jk456445** [human-3d/Human3D#8]
Hello, I downloaded the checkpoint you provided and would like to use your model to segment my point cloud for human bodies. However, I'm not quite sure about the correct procedure.
I am not sure which code to use and where to put my own data.
Could you please guide me on how to execute this? 
Thank you.

**Comment by DzigaVertoff** [comment]
> Hello, I downloaded the checkpoint you provided and would like to use your model to segment my point cloud for human bodies. However, I'm not quite sure about the correct procedure. I am not sure which code to use and where to put my own data. Could you please guide me on how to execute this? Thank you.

Did you solved in some way?
